XTA, FTA, MTA and CTA call graph algorithms
stg-tud/opal-backup pull request #26
Opened 2020-01-07 09:55 UTC by florian-kuebler

PR is migrated from Bitbucket#533.
Implemented by Andreas (@a10r). 

Adds the 4 propagation-based call graph construction algorithms proposed by Tip and Palsberg: XTA, FTA, MTA and CTA.

2020-01-08 09:06 UTC, florian-kuebler reviewed
Looks good in general. Please address comments before merging.

2020-01-08 09:06 UTC, florian-kuebler commented on DEVELOPING_OPAL/validate/src/test/java/org/opalj/fpcf/properties/callgraph/DirectCall.java
> + * Taken from JCG project.
Should we add a dependency to JCG?

2020-01-08 09:06 UTC, florian-kuebler commented on DEVELOPING_OPAL/validate/src/test/java/org/opalj/fpcf/properties/callgraph/DirectCalls.java
> + * Taken from JCG project.
Should we add a dependency to JCG

2020-01-08 09:06 UTC, florian-kuebler commented on DEVELOPING_OPAL/validate/src/test/scala/org/opalj/fpcf/CallGraphTests.scala
> +        //configuredEntryPoint(baseConfig, "org/opalj/fpcf/fixtures/callgraph/xta/FieldFlows", "main")
please remove unused code

2020-01-08 09:06 UTC, florian-kuebler commented on DEVELOPING_OPAL/validate/src/test/scala/org/opalj/fpcf/CallGraphTests.scala
> +    // TODO AB debug stuff, remove later
please remove debug code

2020-01-08 09:06 UTC, florian-kuebler commented on DEVELOPING_OPAL/validate/src/test/scala/org/opalj/fpcf/CallGraphTests.scala
> +            Set("AvailableTypes")
shouldn't this test also validate the Callees?

2020-01-08 09:06 UTC, florian-kuebler commented on OPAL/br/src/main/scala/org/opalj/br/ClassHierarchy.scala
> +    def rootTypes(types: UIDSet[ReferenceType]): UIDSet[ReferenceType] = {
I think this method would lead to confusion with the `rootClassTypesIterator` and the `leafClassTypesIterator`.
Furthermore, using the `leafClassTypesIterator` (if java.lang.Object is not in the given set), the same functionality could be implemented in linear time (instead of quadratic runtime).

2020-01-08 09:06 UTC, florian-kuebler commented on OPAL/tac/src/main/scala/org/opalj/tac/cg/PropagationBasedCallGraphKeys.scala
> +    def setEntitySelector(): SetEntitySelector
Isn't this supposed to be a getter, rather than a setter?

2020-01-08 09:06 UTC, florian-kuebler commented on OPAL/tac/src/main/scala/org/opalj/tac/fpcf/analyses/cg/xta/ExternalWorld.scala
> + * Entity which is used for types flow from/to the "external world".
please add `@author` annotation.

2020-01-08 09:06 UTC, florian-kuebler commented on OPAL/tac/src/main/scala/org/opalj/tac/fpcf/analyses/cg/xta/SetEntitySelector.scala
> +trait SetEntitySelector extends (Entity ⇒ SetEntity)
I'd suggest to slightly rename the trait and the subclasses.

2020-01-08 09:06 UTC, florian-kuebler commented on OPAL/tac/src/main/scala/org/opalj/tac/fpcf/analyses/cg/xta/package.scala
> +package object xta {
please add author information

2020-01-08 09:06 UTC, florian-kuebler commented on OPAL/tac/src/main/scala/org/opalj/tac/fpcf/analyses/cg/xta/package.scala
> +    type SetEntity = Entity
as state above, i would rename "set entity"

2020-01-08 09:06 UTC, florian-kuebler commented on OPAL/tac/src/main/scala/org/opalj/tac/fpcf/analyses/cg/xta/TypePropagationTrace.scala
> + * TODO AB This is for debugging and evaluation, to be removed later.
I'd argue that this class is useful and should not be removed. In particular, as it seems to add no additional overhead.

2020-01-08 09:06 UTC, florian-kuebler commented on OPAL/tac/src/main/scala/org/opalj/tac/fpcf/analyses/cg/xta/PropagationBasedCallGraphAnalysis.scala
> +        // TODO: Document what happens here
please address this todo before merging the CL

2020-01-08 09:06 UTC, florian-kuebler commented on OPAL/tac/src/main/scala/org/opalj/tac/fpcf/analyses/cg/xta/InstantiatedTypesBasedEntryPointsAnalysis.scala
> +            propertyStore(project, InstantiatedTypes.key)
shouldn't you use `se` here as entity?

2020-01-08 09:06 UTC, florian-kuebler commented on OPAL/tac/src/main/scala/org/opalj/tac/fpcf/analyses/cg/xta/ArrayInstantiationsAnalysis.scala
> +    override def uses: Set[PropertyBounds] = Set.empty
It uses the TACAI, right?

2020-01-08 09:06 UTC, florian-kuebler commented on OPAL/tac/src/main/scala/org/opalj/tac/fpcf/analyses/cg/xta/InstantiatedTypesAnalysis.scala
> +        if (caller.name != "<init>") {
please add a comment here (maybe also in the original version)

2020-01-08 09:06 UTC, florian-kuebler commented on OPAL/tac/src/main/scala/org/opalj/tac/fpcf/analyses/cg/xta/InstantiatedTypesAnalysis.scala
> + *
We should also state (here and in the original version), why we are not just using "new" instructions to identify instantiations, i.e. because of reflection.

2020-01-08 09:06 UTC, florian-kuebler commented on OPAL/tac/src/main/scala/org/opalj/tac/fpcf/analyses/cg/xta/InstantiatedTypesAnalysis.scala
> + * This analysis is adapted from the RTA version. Instead of adding the instantiations to the type
We should probably refactor both versions, to either combine both, or to abstract the common code.

2020-01-08 09:06 UTC, florian-kuebler commented on OPAL/tac/src/main/scala/org/opalj/tac/fpcf/analyses/cg/xta/InstantiatedTypesAnalysis.scala
> +        // there must either be a new of the `declaredType`
"either ... " or?

2020-01-21 14:32 UTC, mreif commented on DEVELOPING_OPAL/validate/src/test/java/org/opalj/fpcf/properties/callgraph/DirectCall.java
> + * Taken from JCG project.
That might make sense. We can probably build an integration test that ensures that the JCG results didn't change.

2020-01-21 15:04 UTC, mreif commented on DEVELOPING_OPAL/validate/src/test/java/org/opalj/fpcf/properties/callgraph/DirectCall.java
> + * Taken from JCG project.
We should remove this class because it's not used in any test case. All the test code is only annotated with the "@AvailableTypes" Annotation.

2020-01-21 15:05 UTC, mreif commented on DEVELOPING_OPAL/validate/src/test/java/org/opalj/fpcf/properties/callgraph/DirectCalls.java
> + * Taken from JCG project.
Same here, if I didn't miss something we can remove the class.

2020-01-22 10:32 UTC, mreif reviewed
Looks, in general, alright, but there are few things that should be done before merging.

2020-01-22 10:32 UTC, mreif commented on DEVELOPING_OPAL/validate/src/test/scala/org/opalj/fpcf/CallGraphTests.scala
> +            Set("AvailableTypes")
I agree, however, the expected callees are never annotated.

2020-01-22 10:32 UTC, mreif commented on OPAL/br/src/main/scala/org/opalj/br/ClassHierarchy.scala
> +    def rootTypes(types: UIDSet[ReferenceType]): UIDSet[ReferenceType] = {
Additionally, I'm not sure whether this method must be defined on the ```ClassHierarchy```.

2020-01-22 10:32 UTC, mreif commented on OPAL/tac/src/main/scala/org/opalj/tac/fpcf/analyses/cg/xta/ArrayInstantiationsAnalysis.scala
> +    override def uses: Set[PropertyBounds] = Set.empty
As far as I'm concerned it doesn't. At least it seems like that the TAC remains unused within the analysis. But I'm honestly not sure whether the TAC is beneficial here.

2020-01-22 10:32 UTC, mreif commented on OPAL/tac/src/main/scala/org/opalj/tac/fpcf/analyses/cg/xta/InstantiatedTypesAnalysis.scala
> + * This analysis is adapted from the RTA version. Instead of adding the instantiations to the type
Agreed.

2020-01-22 10:32 UTC, mreif commented on OPAL/tac/src/main/scala/org/opalj/tac/fpcf/analyses/cg/xta/InstantiatedTypesAnalysis.scala
> + *
If we provide a common abstraction or merge them, we hopefully don't have to duplicate all the comments.

2020-01-22 10:32 UTC, mreif commented on OPAL/tac/src/main/scala/org/opalj/tac/fpcf/analyses/cg/xta/InstantiatedTypesAnalysis.scala
> +            if !seenCallers.contains(caller)
Shouldn't we use a set here?

2020-01-22 10:32 UTC, mreif commented on OPAL/tac/src/main/scala/org/opalj/tac/fpcf/analyses/cg/xta/InstantiatedTypesAnalysis.scala
> +        // whose element type is an ObjectType. Arrays of primitive types can be ignored.
Why ArrayTypes with ObjectType element types? What's about multi-dimensional arrays where the element type is a ReferenceType?

2020-01-22 10:32 UTC, mreif commented on OPAL/tac/src/main/scala/org/opalj/tac/fpcf/analyses/cg/xta/InstantiatedTypesBasedEntryPointsAnalysis.scala
> +            propertyStore(project, InstantiatedTypes.key)
I'm not getting why this is needed at all. The entry points should be the same as in the RTA version of the call graph since they only depend on the initially instantiated types.

2020-01-22 10:32 UTC, mreif commented on OPAL/tac/src/main/scala/org/opalj/tac/fpcf/analyses/cg/xta/SetEntitySelector.scala
> +trait SetEntitySelector extends (Entity ⇒ SetEntity)
Do you have name suggestions? TypeSetEntitySelector?

2020-01-22 10:32 UTC, mreif commented on OPAL/tac/src/main/scala/org/opalj/tac/fpcf/analyses/cg/xta/TypePropagationTrace.scala
> + * TODO AB This is for debugging and evaluation, to be removed later.
Indeed, tracing does not hurt for debugging purposes. However, I'm unsure about the overhead part.

2020-01-22 10:32 UTC, mreif commented on OPAL/tac/src/main/scala/org/opalj/tac/fpcf/analyses/cg/xta/TypePropagationTrace.scala
> +            val file = new FileOutputStream(new File(s"C:\\Users\\Andreas\\Dropbox\\Masterarbeit\\traces\\trace${Instant.now.getEpochSecond}.txt"))
This should be changed before merging. This path should be either set somewhere in opal or should be made configurable.

2020-01-22 10:32 UTC, mreif commented on OPAL/tac/src/main/scala/org/opalj/tac/fpcf/analyses/cg/xta/package.scala
> +    type SetEntity = Entity
Again, suggestions? I don't have any good idea that just feels alright.

2020-01-22 10:36 UTC, mreif requested changes
Things that should be addressed: 
 - fix comments
- remove debug code
- find a better name for _SetEntity_
- We should figure out whether the ```InstantiatedTypeEntryPointsanalysis``` really should use the provided ```se``` variable (That's probably something for discusison)
- some classes lack @author tags
- some classes lack documentation
- hopefully, I didn't forget anything
Edited by @florian-kuebler: 
- base class for instantiated type analyses

2020-01-23 15:30 UTC, florian-kuebler commented on OPAL/tac/src/main/scala/org/opalj/tac/fpcf/analyses/cg/xta/ArrayInstantiationsAnalysis.scala
> +    override def uses: Set[PropertyBounds] = Set.empty
But the base class does, so for the frameworks correctness, it should be there. Just removing the overridden method should be sufficient.

2020-01-24 08:58 UTC, florian-kuebler commented on DEVELOPING_OPAL/validate/src/test/scala/org/opalj/fpcf/CallGraphTests.scala
> +            Set("AvailableTypes")
I added a TODO. We should extend that test suite and provide more examples.

2020-01-24 09:10 UTC, florian-kuebler commented on OPAL/br/src/main/scala/org/opalj/br/ClassHierarchy.scala
> +    def rootTypes(types: UIDSet[ReferenceType]): UIDSet[ReferenceType] = {
It is only used in the TypePropagationState, lets move it there. I'll add an IMPROVE, to get rid of the quadratic time at some point.

2020-01-24 09:24 UTC, florian-kuebler commented on OPAL/tac/src/main/scala/org/opalj/tac/fpcf/analyses/cg/xta/InstantiatedTypesAnalysis.scala
> + * This analysis is adapted from the RTA version. Instead of adding the instantiations to the type
I added a TODO, however we should probably address this before merging

2020-01-24 09:32 UTC, florian-kuebler commented on OPAL/tac/src/main/scala/org/opalj/tac/fpcf/analyses/cg/xta/InstantiatedTypesAnalysis.scala
> +            if !seenCallers.contains(caller)
What do you mean by this? seenCallers is already a set.

2020-01-24 09:58 UTC, florian-kuebler commented on OPAL/tac/src/main/scala/org/opalj/tac/fpcf/analyses/cg/xta/InstantiatedTypesAnalysis.scala
> +        // whose element type is an ObjectType. Arrays of primitive types can be ignored.
I think the description is correct. "we keep track of all array types we see, as well as subtypes and lower-dimensional types". The element type in Opal is the innermost type, e.g. int[][][] has element type int.

2020-01-24 10:16 UTC, florian-kuebler commented on OPAL/tac/src/main/scala/org/opalj/tac/fpcf/analyses/cg/xta/InstantiatedTypesBasedEntryPointsAnalysis.scala
> +            propertyStore(project, InstantiatedTypes.key)
I am still not convinced here. The analyze function gets executed as soon as there is a first value for the instantiated types of that `se`. Why should we then look for the instantiated types of the project, for all those entities.
If we know that the instantiated types for a project will always be the union of all instantiated types sets, then a triggered analysis is an overkill. you would need to schedule an eager analysis for the instantiated types of a project then and stay updated.
If I remember correctly and got the comment above right, such analysis already exists.

2020-01-24 10:18 UTC, florian-kuebler commented on OPAL/tac/src/main/scala/org/opalj/tac/fpcf/analyses/cg/xta/InstantiatedTypesBasedEntryPointsAnalysis.scala
> +    private val globallySeenTypes: mutable.Set[ObjectType] = mutable.Set[ObjectType]()
This set should be better threadsafe, right?

2020-01-24 10:24 UTC, florian-kuebler commented on OPAL/tac/src/main/scala/org/opalj/tac/fpcf/analyses/cg/xta/TypePropagationTrace.scala
> +@elidable(elidable.ASSERTION)
shouldn't that annotation only be used on methods?

2020-01-28 09:02 UTC, mreif approved these changes

2020-01-28 09:03 UTC, merged