Added a PointsTo Analysis
stg-tud/opal-backup pull request #7
Opened 2020-01-06 15:49 UTC by florian-kuebler

2020-01-28 14:12 UTC, errt requested changes
Partial review for the first 35 files.

2020-01-28 14:12 UTC, errt commented on DEVELOPING_OPAL/demos/src/main/scala/org/opalj/fpcf/analyses/PRATaintAnalysis.scala
> +/* BSD 2-Clause License - see OPAL/LICENSE for details. */
I don't think this file should be included in this PR.

2020-01-28 14:12 UTC, errt commented on DEVELOPING_OPAL/tools/src/main/scala/org/opalj/support/info/CallGraph.scala
> +    private val algorithmRegex = "-algorithm=(CHA|RTA|PointsTo|PointsToScala)".r
I suggest we remove the PointsToScala code completely from this PR. It was for evaluation purposes only.

2020-01-28 14:12 UTC, errt commented on DEVELOPING_OPAL/tools/src/main/scala/org/opalj/support/info/CallGraph.scala
> +                    !p.startsWith("-writePointsToSets=") && // TODO: implement this
Should be implemented before merging.

2020-01-28 14:12 UTC, errt commented on DEVELOPING_OPAL/tools/src/main/scala/org/opalj/support/info/CallGraph.scala
> +        project.getOrCreateProjectInformationKeyInitializationData(
Remove this. It was for evaluation purposes only and PKECPropertyStore is broken badly.

2020-01-28 14:12 UTC, errt commented on DEVELOPING_OPAL/tools/src/main/scala/org/opalj/support/info/CallGraph.scala
> +            println(statistic.mkString("\n"))
Remove this println or make it configurable.

2020-01-28 14:12 UTC, errt commented on DEVELOPING_OPAL/tools/src/main/scala/org/opalj/support/info/CallGraph.scala
> +            /*
Remove large commented out sections that were used for testing purposes.

2020-01-28 14:12 UTC, errt commented on DEVELOPING_OPAL/tools/src/main/scala/org/opalj/support/info/CallGraph.scala
> +        // TODO: Implement output files
Output file is written below, PointsTo file is not yet implemented though.

2020-01-28 14:12 UTC, errt commented on DEVELOPING_OPAL/tools/src/main/scala/org/opalj/support/info/Purity.scala
> +        project.getOrCreateProjectInformationKeyInitializationData(
Remove, this was for evaluation purposes and PKECPropertyStore is badly broken.

2020-01-28 14:12 UTC, errt commented on OPAL/br/src/main/scala/org/opalj/br/analyses/cg/EntryPointFinder.scala
> +        }.filterNot(ep ⇒ ep.classFile.thisType == ObjectType("WrapperGenerator"))
Please add a comment for why this is needed.

2020-01-28 14:40 UTC, florian-kuebler commented on DEVELOPING_OPAL/tools/src/main/scala/org/opalj/support/info/CallGraph.scala
> +    private val algorithmRegex = "-algorithm=(CHA|RTA|PointsTo|PointsToScala)".r
I partly agree, the question would be where to put this for reproducibility of the evaluation?

2020-01-28 14:49 UTC, errt commented on DEVELOPING_OPAL/tools/src/main/scala/org/opalj/support/info/CallGraph.scala
> +    private val algorithmRegex = "-algorithm=(CHA|RTA|PointsTo|PointsToScala)".r
Keep the/a branch with it?

2020-01-28 15:32 UTC, errt requested changes
Done with review.

2020-01-28 15:32 UTC, errt commented on OPAL/br/src/main/scala/org/opalj/br/fpcf/properties/pointsto/AllocationSitePointsToSetScala.scala
> +/* BSD 2-Clause License - see OPAL/LICENSE for details. */
Remove, part of the Scala PointsTo evaluation.

2020-01-28 15:32 UTC, errt commented on OPAL/br/src/main/scala/org/opalj/br/fpcf/properties/pointsto/PointsToSetLike.scala
>  /**
Document...

2020-01-28 15:32 UTC, errt commented on OPAL/br/src/main/scala/org/opalj/br/fpcf/properties/pointsto/TypeBasedPointsToSet.scala
>  }
Remove TODO in line 23, we have that as AllocationSitePointsToSet now.

2020-01-28 15:32 UTC, errt commented on OPAL/br/src/main/scala/org/opalj/br/fpcf/properties/pointsto/package.scala
> +    // we encode allocation sites (method, pc, emptyArray, typeid tuples) as longs
Add comment on which bits in the long encode what.

2020-01-28 15:32 UTC, errt commented on OPAL/si/src/main/resources/reference.conf
> +  //fpcf.seq.PKESequentialPropertyStore.TasksManager = "ManyDependeesOfDirectDependersLast"
Remove commented out line.

2020-01-28 15:32 UTC, errt commented on OPAL/si/src/main/scala/org/opalj/fpcf/PropertyComputationResult.scala
> +case class PrecomputedPartialResult[E >: Null <: Entity, P >: Null <: Property](
Document

2020-01-28 15:32 UTC, errt commented on OPAL/si/src/main/scala/org/opalj/fpcf/par/PKECPropertyStore.scala
> +        potentiallyIdemPotentUpdate: Boolean     = true // TODO: THIS IS A HORRIBLE WORKAROUND
I suggest to revert this change, even if it breaks the Store even further.

2020-01-28 15:32 UTC, errt commented on OPAL/si/src/main/scala/org/opalj/fpcf/seq/TasksManager.scala
> +        //if (wt ne null) {
Remove commented out code (there is more in the next lines).

2020-01-28 15:32 UTC, errt commented on OPAL/si/src/test/scala/org/opalj/fpcf/PropertyComputationResultsTest.scala
> +                PartialResult.id
List should probably include InterimPartialResult and PrecomputedPartialResult. Also, there are no tests here for any of the PartialResult types.

2020-01-28 15:32 UTC, errt commented on OPAL/tac/src/main/resources/reference.conf
> +//          {
Remove comment, this was commented out for evaluation purposes against Doop only.

2020-01-28 15:32 UTC, errt commented on OPAL/tac/src/main/resources/reference.conf
> +//          {
As above, remove comment.

2020-01-28 15:32 UTC, errt commented on OPAL/tac/src/main/scala/org/opalj/tac/cg/AllocationSiteBasedPointsToScalaCallGraphKey.scala
> +/* BSD 2-Clause License - see OPAL/LICENSE for details. */
Remove file, part of the Scala PointsTo eval.

2020-01-28 15:32 UTC, errt commented on OPAL/tac/src/main/scala/org/opalj/tac/cg/PropagationBasedCallGraphKeys.scala
>  import org.opalj.br.analyses.ProjectInformationKeys
Would it be possible to merge RTA into this?

2020-01-28 15:32 UTC, errt commented on OPAL/tac/src/main/scala/org/opalj/tac/cg/TypeBasedPointsToCallGraphKey.scala
> +        //ConfiguredNativeMethodsPointsToAnalysisScheduler,
Why are these commented out? Either remove comment or remove lines, depending on what is correct.

2020-01-28 15:32 UTC, errt commented on OPAL/tac/src/main/scala/org/opalj/tac/fpcf/analyses/TACAIBasedAnalysisState.scala
> +    assert(_tacDependee == null || (_tacDependee.hasUBP && _tacDependee.ub.tac.isDefined))
eq null

2020-01-28 15:32 UTC, errt commented on OPAL/tac/src/main/scala/org/opalj/tac/fpcf/analyses/cg/AbstractCallGraphAnalysis.scala
> +    /*TODO private[this]*/ def handleVirtualCall(
Is there still a valid reason for commenting out this modifier?

2020-01-28 15:32 UTC, errt commented on OPAL/tac/src/main/scala/org/opalj/tac/fpcf/analyses/cg/DoPrivilegedPointsToCGAnalysis.scala
> + * TODO: This analysis produces direct calls from AccessController.doPrivileged to the corresponding
Is it possible to change this easily?

2020-01-28 15:32 UTC, errt commented on OPAL/tac/src/main/scala/org/opalj/tac/fpcf/analyses/cg/DoPrivilegedPointsToScalaCGAnalysis.scala
> +/* BSD 2-Clause License - see OPAL/LICENSE for details. */
Remove file, part of the Scala PointsTo eval.

2020-01-28 15:32 UTC, errt commented on OPAL/tac/src/main/scala/org/opalj/tac/fpcf/analyses/cg/pointsto/PointsToBasedThreadRelatedCallsScalaAnalysisScheduler.scala
> +/* BSD 2-Clause License - see OPAL/LICENSE for details. */
Remove file, part of the Scala PointsTo eval.

2020-01-28 15:32 UTC, errt commented on OPAL/tac/src/main/scala/org/opalj/tac/fpcf/analyses/cg/reflection/VarargsUtil.scala
> +                /*if (cfg.bb(uses.head) != cfg.bb(uses.last)) {
If the code changes were actually save, remove commented out code.

2020-01-28 15:32 UTC, errt commented on OPAL/tac/src/main/scala/org/opalj/tac/fpcf/analyses/pointsto/AbstractPointsToAnalysis.scala
> + *
Document

2020-01-28 15:32 UTC, errt commented on OPAL/tac/src/main/scala/org/opalj/tac/fpcf/analyses/pointsto/AbstractPointsToAnalysis.scala
> +        // todo: we have to handle the exceptions that might implicitly be thrown by this method
todo -> TODO

2020-01-28 15:32 UTC, errt commented on OPAL/tac/src/main/scala/org/opalj/tac/fpcf/analyses/pointsto/AllocationSiteBasedPointsToAnalysisScala.scala
> +/* BSD 2-Clause License - see OPAL/LICENSE for details. */
Remove file, part of Scala PointsTo eval.

2020-01-28 15:32 UTC, errt commented on OPAL/tac/src/main/scala/org/opalj/tac/fpcf/analyses/pointsto/AllocationSiteBasedScalaAnalysis.scala
> +/* BSD 2-Clause License - see OPAL/LICENSE for details. */
Remove file, part of Scala PointsTo eval.

2020-01-28 15:32 UTC, errt commented on OPAL/tac/src/main/scala/org/opalj/tac/fpcf/analyses/pointsto/ArraycopyPointsToAnalysis.scala
> +abstract class ArraycopyPointsToAnalysis private[pointsto] ( final val project: SomeProject)
Document

2020-01-28 15:32 UTC, errt commented on OPAL/tac/src/main/scala/org/opalj/tac/fpcf/analyses/pointsto/ArraycopyPointsToAnalysisScala.scala
> +/* BSD 2-Clause License - see OPAL/LICENSE for details. */
Remove file, part of Scala PointsTo eval.

2020-01-28 15:32 UTC, errt commented on OPAL/tac/src/main/scala/org/opalj/tac/fpcf/analyses/pointsto/ConfiguredMethodsPointsToAnalysisScala.scala
> +/* BSD 2-Clause License - see OPAL/LICENSE for details. */
Remove file, part of Scala PointsTo eval.

2020-01-28 15:32 UTC, errt commented on OPAL/tac/src/main/scala/org/opalj/tac/fpcf/analyses/pointsto/PointsToAnalysisBase.scala
> +trait PointsToAnalysisBase extends AbstractPointsToBasedAnalysis {
Document

2020-01-28 15:32 UTC, errt commented on OPAL/tac/src/main/scala/org/opalj/tac/fpcf/analyses/pointsto/PointsToEntities.scala
> +case class ArrayEntity[ElementType](element: ElementType)
Document

2020-01-28 15:32 UTC, errt commented on OPAL/tac/src/main/scala/org/opalj/tac/fpcf/analyses/pointsto/TamiFlexKey.scala
> +        //TODO We shoul really split these according to the source (i.e., the reflection method) to
Todo seems outdated.

2020-01-28 15:32 UTC, errt commented on OPAL/tac/src/main/scala/org/opalj/tac/fpcf/analyses/pointsto/TamiFlexPointsToAnalysis.scala
> +abstract class AllocationSiteBasedTamiFlexPointsToAnalysis private[analyses] (
Document

2020-01-28 15:32 UTC, errt commented on OPAL/tac/src/main/scala/org/opalj/tac/fpcf/analyses/pointsto/TamiFlexPointsToAnalysisScala.scala
> +/* BSD 2-Clause License - see OPAL/LICENSE for details. */
Remove file, part of Scala PointsTo eval.

2020-01-28 15:32 UTC, errt commented on OPAL/tac/src/main/scala/org/opalj/tac/fpcf/analyses/pointsto/TypeBasedAnalysis.scala
> +trait TypeBasedAnalysis extends AbstractPointsToBasedAnalysis {
Document

2020-01-28 15:32 UTC, errt commented on OPAL/tac/src/main/scala/org/opalj/tac/fpcf/analyses/pointsto/UnsafePointsToAnalysis.scala
> +abstract class UnsafePointsToAnalysis private[pointsto] ( final val project: SomeProject)
Document

2020-01-28 15:32 UTC, errt commented on OPAL/tac/src/main/scala/org/opalj/tac/fpcf/analyses/pointsto/UnsafePointsToAnalysisScala.scala
> +/* BSD 2-Clause License - see OPAL/LICENSE for details. */
Remove file, part of Scala PointsTo eval.

2020-01-28 15:32 UTC, errt commented on OPAL/tac/src/main/scala/org/opalj/tac/fpcf/analyses/pointsto/package.scala
> +    def toEntity(
Document

2020-01-30 07:35 UTC, florian-kuebler commented on OPAL/tac/src/main/scala/org/opalj/tac/cg/PropagationBasedCallGraphKeys.scala
>  import org.opalj.br.analyses.ProjectInformationKeys
Yes, but refactoring (and subsequent performance evaluation) is quite a bit of work.
As  discussed within #26, I suggest to to this refactoring in a separate PR.

2020-01-30 07:38 UTC, florian-kuebler commented on OPAL/tac/src/main/scala/org/opalj/tac/fpcf/analyses/cg/DoPrivilegedPointsToCGAnalysis.scala
> + * TODO: This analysis produces direct calls from AccessController.doPrivileged to the corresponding
Yep, should be not to hard to do.

2020-01-30 09:46 UTC, florian-kuebler commented on OPAL/br/src/main/scala/org/opalj/br/fpcf/properties/pointsto/TypeBasedPointsToSet.scala
> +    ): TypeBasedPointsToSet = ???
implement

2020-01-30 09:46 UTC, florian-kuebler commented on OPAL/br/src/main/scala/org/opalj/br/fpcf/properties/pointsto/TypeBasedPointsToSet.scala
> +    ): TypeBasedPointsToSet = ???
implement

2020-01-30 09:46 UTC, florian-kuebler commented on OPAL/br/src/main/scala/org/opalj/br/fpcf/properties/pointsto/TypeBasedPointsToSet.scala
> +    ): TypeBasedPointsToSet = ???
implement

2020-01-30 09:46 UTC, florian-kuebler commented on OPAL/br/src/main/scala/org/opalj/br/fpcf/properties/pointsto/TypeBasedPointsToSet.scala
> +        included(other) // todo: implement correct version
implement

2020-01-30 12:24 UTC, florian-kuebler commented on OPAL/si/src/main/scala/org/opalj/fpcf/PropertyComputationResult.scala
> +case class PrecomputedPartialResult[E >: Null <: Entity, P >: Null <: Property](
We should test whether this is useful at all

2020-01-30 12:27 UTC, florian-kuebler commented on OPAL/tac/src/main/scala/org/opalj/tac/fpcf/analyses/cg/pointsto/AbstractPointsToBasedCallGraphAnalysis.scala
> + * TODO: This analysis is currently copy&paste and should be refactored
We should refactor this

2020-02-03 08:41 UTC, errt approved these changes

2020-02-03 08:41 UTC, merged